### ISSUE TITLE
Adding more flexibility to modify premitive transistor template

### ISSUE THREAD

**Issue by ChrisZonghaoLi** [niftylab/laygo2#25]
From what I understand from your presentation here at MOSAIC (https://www.youtube.com/watch?v=RI0rDiXslOE), the generation of the mos primitive cells (the final yaml definition) involves many steps, which to me is quite cumbersome (need BAG, LAYGO1, and the conversion script). In addition, all the provided examples here are covering only digital examples where the transistor's W and L are fixed to some numbers, and the only degree of freedom to tweak their dimension is using NF. I guess the reason behind this is your primitive mos instances were written using some template that already forces W and L to some number (let me know if I am wrong). This approach might be fine when you are doing finfet stuff, but for planar CMOS, you would like people to decide the value for W and L more friendly. Also, it is completely possible when each finger size is different, and I am not sure if the template approach is feasible with different finger dimensions. Do you have any quick solution to this? Thanks.

**Comment by jdhan** [comment]
Hello, thanks for sharing your helpful idea. Here are my comments.

- For the laygo2_tech.yaml construction, we understand it takes several steps to generate the final yaml file, as we haven't implemented the layout import function (we have an internal function to do so, but haven't released it for some issues). While it would be appreciated to implement the function by outside contributors, the yaml files can also be constructed manually or by using Python scripts with parameters (without extracting them from the layout).

- For the parameterization of width, that function can be supported by specifying the "pcell_params" dictionary in the Instance.params dictionary (which can also be configured by ParameterizedInstanceTemplate or UserDefinedTemplate) based on the input width/length parameters. The placement/routing grids can be reconfigured based on the parameters as well. This width/length parameterization is tested and verified by external users so I believe it should work smoothly.
  See the line 202 in https://github.com/niftylab/laygo2/blob/master/laygo2/interface/skill.py for more information.

**Comment by ChrisZonghaoLi** [comment]
Thanks for the prompt reply. In your second comment, when you said "The placement/routing grids can be reconfigured based on the parameters as well", does this involve any human intervention, or the PnR grids will be updated somehow automatically? I suppose every time once the width/length is changed, the whole PnR grid templates also need to be changed, am I right?

The reason I am asking this is, I am planning to have some sort of layout generation baked into a whole circuit optimization loop, so you can imagine the optimizer is constantly searching for the transistor dimensions until the target specs are satisfied (kind of like the BagNet paper if you are familiar with, but I never get the chance to know their detailed implementations). If the templates need to be reconfigured every time due to the change of transistor width/length, the whole procedure will be quite tedious and intractable. 

Would you think laygo2 is a good applicable option in my scenario? Thanks.

**Comment by ChrisZonghaoLi** [comment]
Thanks, and I assume the grid size can be defined through the `laygo2_tech.yaml` file right? Do I have to also change the placement template as well?

**Comment by ChrisZonghaoLi** [comment]
Okay, I think I may find the answer to my question. It seems that all the transistor primitives are stored inside the `skywater130_microtemplates_dense`, and what laygo does is just instantiating these primitives.

**Comment by jdhan** [comment]
Yes, you can always redefine the yaml file (manually or by using a dedicated script) or redefine the template / grid objects by modifying load_templates() and load_grids() in laygo_tech
