### ISSUE TITLE
Update GitHub About Documentation URL

### ISSUE THREAD

**Issue by curtisma** [niftylab/laygo2#4]
The link URL in the About section on GitHub is out of date and opens a broken site.  It should be updated to the new documentation URL:
https://laygo2.github.io/

![image](https://user-images.githubusercontent.com/4685385/189260086-bb9fe154-0fb7-402c-a4c7-adeb0aeddd9d.png)

**Comment by jdhan** [comment]
Thanks for pointing this out. The link is fixed now.
