### ISSUE TITLE
Fix NAND Getting Started Example Error

### ISSUE THREAD

**Issue by curtisma** [niftylab/laygo2#5]
I'm trying to run the NAND example from the [getting started instructions](https://laygo2.github.io/examples_link.html#simple-gate-generation).  However, when I run it I get an error suggesting the 'xcolor' and 'ycolor' parameters need to be defined in the example technology.  Can you help fix this example?

## Error

Note: I moved the "examples/" directory into "laygo2/examples/" so I can use importlib.resources.files to get the tech_params filepath easily

```bash
/space/mayberc/envs/mambaforge/envs/laygo2-dev/bin/python /prj/ids_dev/work_libs/mayberc/laygo2/laygo2/examples/simple_gates/nand_generate.py
Load templates
<laygo2.object.template.UserDefinedTemplate object at 0x7efdc7b43e20> name: pmos, class: UserDefinedTemplate, 
<laygo2.object.template.UserDefinedTemplate object at 0x7efdc7b43e50> name: nmos, class: UserDefinedTemplate, 
Load grids
Traceback (most recent call last):
  File "/prj/ids_dev/work_libs/mayberc/laygo2/laygo2/examples/simple_gates/nand_generate.py", line 55, in <module>
    grids = tech.load_grids(templates=templates)
  File "/prj/ids_dev/work_libs/mayberc/laygo2/laygo2/examples/technology_example/technology_example_grids.py", line 50, in load_grids
    g = laygo2.object.grid.RoutingGrid(name=gname, vgrid=gv, hgrid=gh,
TypeError: __init__() missing 2 required positional arguments: 'xcolor' and 'ycolor'
```

## Problematic code
xcolor and ycolor should be passed in.  I assume they should also be in the tech_params yaml file.

Starting at line 50 of technology_example_grids.py:

``` python
g = laygo2.object.grid.RoutingGrid(name=gname, vgrid=gv, hgrid=gh,
                                               vwidth=vwidth, hwidth=hwidth,
                                               vextension=vextension, hextension=hextension,
                                               vlayer=vlayer, hlayer=hlayer,
                                               pin_vlayer=pin_vlayer, pin_hlayer=pin_hlayer,
                                               viamap=viamap, primary_grid=primary_grid)
```

**Comment by jdhan** [comment]
Looks like you already fixed the code. Thanks!
(I guess at some point we need to make the xcolor/ycolor arguments in RoutingGrid optional ones, as they are not required in planar MPT.

**Comment by curtisma** [comment]
Oh, no, I haven't fixed the issue yet.  I just made the other updates in that draft PR to get to the point where I found this error.

Do you think it will fix the issue if I just make those parameters optional?  I'll try it and see.

**Comment by jdhan** [comment]
Okay so, it looks like we have two versions of the technology example for some reason, one in laygo2/examples/technology_examples and the other one in laygo2/examples/quick_start/quick_start_tech

The second one works well as it automatically generates xcolor and ycolor lists in technology_example_grids.py:

`
            xcolor = list()
            if 'xcolor' in grid['vertical'].keys():
                if grid['vertical']['xcolor'] == 'not MPT':
                    xcolor = np.array(['not MPT']*vlayer.shape[0], dtype=object)
                else:
                    xcolor.append( grid['vertical']['xcolor'])
            else:
                xcolor = np.array(['not MPT']*vlayer.shape[0], dtype=object)

            ycolor = list()
            if 'ycolor' in grid['horizontal'].keys():
                if grid['horizontal']['ycolor'] == 'not MPT':
                    ycolor = np.array(['not MPT']*hlayer.shape[0], dtype=object)
                else:
                    ycolor.append( grid['horizontal']['ycolor'])
            else:
                ycolor = np.array(['not MPT']*hlayer.shape[0], dtype=object)
`
 
Perhaps we need to make the color parameters in RoutingGrid() and do things like above when the xcolor/ycolor are not received (None).
Feel free to file a merge request if you'd like.

**Comment by curtisma** [comment]
Ok, so I made the color parameters optional and that fixed the issue.  I'll submit a PR with the update shortly.

However both the nand_generate and quick_start examples try to generate a gds but throw an exception:

`Exception: GDS support is currently disabled. Will be reinvented by using gds-tk.`

Why is GDS support currently disabled?

**Comment by curtisma** [comment]
Also, are the "examples/technology_example" and "examples/quick_start/quick_start_tech" identical?

**Comment by jdhan** [comment]
Thanks, make sure you add the xcolor/ycolor grid constructions if they are not received in __init__.py.

GDS export is currently disabled. I think we should reinvent the wheel by using gds-tk, which is used frequently in many open-source projects.
https://heitzmann.github.io/gdstk/

And yes, I think we need to delete one of them. I guess the quick_start_tech is the latest one.

**Comment by curtisma** [comment]
> Thanks, make sure you add the xcolor/ycolor grid constructions if they are not received in init.py.

Yeah, I set them to None and the example now runs until it tries to export the gds.

> GDS export is currently disabled. I think we should reinvent the wheel by using gds-tk, which is used frequently in many open-source projects.
> https://heitzmann.github.io/gdstk/

Ok, I'll have to look at that package.  You might also consider [gdsfactory](https://gdsfactory.github.io/gdsfactory/).  It looks well-documented and is frequently used in the Photonics community.

**Comment by curtisma** [comment]
If you do use gdstk, you might want to try using conda to install it since they have a [Conda package](https://anaconda.org/conda-forge/gdstk) available for it from conda-forge.  They also have instructions on [installing it using Conda](https://github.com/heitzmann/gdstk#conda).  Then users wouldn't need to compile it from source.

I would recommend installing conda and [mamba](https://mamba.readthedocs.io/en/latest/) using the [mambaforge installer](https://github.com/conda-forge/miniforge#mambaforge).

**Comment by jdhan** [comment]
> Yeah, I set them to None and the example now runs until it tries to export the gds. You can check out the updates in PR https://github.com/niftylab/laygo2/pull/7.
Could you update the request to assign a list composed of 'not MPT' to xcolor (and ycolor) when it's input value is not provided?

>Ok, I'll have to look at that package. You might also consider [gdsfactory](https://gdsfactory.github.io/gdsfactory/). It looks well-documented and feature rich. It is frequently used in the Photonics community.
>If you do use gdstk, you might want to try using conda to install it since they have a [Conda package](https://anaconda.org/conda-forge/gdstk) available for it from conda-forge. They also have instructions on [installing it using Conda](https://github.com/heitzmann/gdstk#conda). Then users wouldn't need to compile it from source.
>I would recommend installing conda and [mamba](https://mamba.readthedocs.io/en/latest/) using the [mambaforge installer](https://github.com/conda-forge/miniforge#mambaforge).

Either gdstk or gdsfactory seems great to me. I mentioned gdstk just because I think that one is currently being used in openroad. But gdsfactory also looks great. You are welcomed to work on it if you'd like (otherwise I'll try to work on it by myself at some point).
